services:
  - type: web
    name: vibe-fearless
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
